comment:
  behavior: default
  layout: reach, diff, flags, files
  require_base: false
  require_changes:
    - 0
  require_head: true
coverage:
  precision: 2
  range:
    - 50.0
    - 80.0
  round: down
  status:
    patch:
      default:
        base: auto
        target: 70.0
        threshold: 5.0
    project:
      default:
        base: auto
        branches: null
        flags: null
        if_ci_failed: error
        if_no_uploads: error
        if_not_found: success
        only_pulls: false
        paths: null
        target: auto
        threshold: 2.0
ignore:
  - ^src/auto_pr/main.py.*
  - (?s:tests/.*/[^\/]*)\Z
  - (?s:.*/__version__\.py)\Z
  - (?s:examples/.*/[^\/]*)\Z
  - (?s:docs/.*/[^\/]*)\Z
  - (?s:scripts/.*/[^\/]*)\Z
